### ISSUE TITLE
First person not working with glb avatars

### ISSUE THREAD

**Issue by AlbertoElias** [ssatguru/BabylonJS-CharacterController#65]
In the testAnimationGroup example which uses a .glb avatar, when scrolling to go into first person mode, it stops right before. If in the same example I change to the .babylon, it works just fine. I've tried with other .glb avatars and same issue. I'm not sure what's different.

**Comment by ssatguru** [comment]
You are right. The issue is that for glb, babylons adds a dummy "__root__ " node at the top. When the ChracterControl  makes the avatar invisible  it is this dummy node that is being made invisible rather than the actual avatr mesh. I should probably check if the root node is "__root__" and if yes then go down the hierarchy looking for the avatar mesh and turn that invisible. I I I would work on this , sometime this week.
thanks for reporting this bug.

**Comment by ssatguru** [comment]
@AlbertoElias  I have put in a fix for this.
https://github.com/ssatguru/BabylonJS-CharacterController/commit/b1712b7bf8055e6fab18178885e3f3ed68246bdd
Fix in 0.4.4-alpha.7 version
Try and let me know if it works for you now

**Comment by AlbertoElias** [comment]
@ssatguru Hey, thanks so much for the extremely quick turnaround. It does work! :)
